/**
 * Generated by scripts/gen-whole-world-ts.js:
 */

export type Point = { x: number; y: number };

export type WholeWorldDescription = {
  colors: Map<string, string>;
  levels: Array<
    | {
        topology: 'rect';
        size: { x: number; y: number };
        colors: { base: string; lava: string; water: string; earth: string };
      }
    | {
        topology: 'torus';
        tilesPerChunk: { x: number; y: number };
        chunksPerLevel: { x: number; y: number };
        colors: { base: string; lava: string; water: string; earth: string };
      }
    | {
        topology: 'daia';
        facetsPerFace: number;
        tilesPerFacet: number;
        colors: Array<{
          base: string;
          lava: string;
          water: string;
          earth: string;
        }>;
      }
  >;
  player: number | undefined;
  locations: Array<number>;
  types: Array<number>;
  inventories: Map<number, Array<number>> | undefined;
  terrain: Array<number> | undefined;
  healths: Map<number, number> | undefined;
  staminas: Map<number, number> | undefined;
  targetLocations: Map<number, number> | undefined;
  targetEntities: Map<number, number> | undefined;
  mechanics: {
    agentTypes: Array<{
      name: string;
      tile: string | undefined;
      wanders: string | undefined;
      dialog: Array<string> | undefined;
      health: number | undefined;
      stamina: number | undefined;
      modes:
        | Array<{
            tile: string;
            holds: string | undefined;
            has: string | undefined;
            hot: boolean | undefined;
            cold: boolean | undefined;
            sick: boolean | undefined;
            health: number | undefined;
            stamina: number | undefined;
            immersed: boolean | undefined;
          }>
        | undefined;
      slots:
        | Array<{
            tile: string;
            held: boolean | undefined;
            pack: boolean | undefined;
          }>
        | undefined;
    }>;
    recipes:
      | Array<{
          agent: string;
          reagent: string;
          product: string;
          byproduct: string | undefined;
          price: number | undefined;
          dialog: string | undefined;
        }>
      | undefined;
    actions:
      | Array<{
          agent: string | undefined;
          patient: string;
          left: string | undefined;
          right: string | undefined;
          effect: string | undefined;
          verb: string;
          items: Array<string> | undefined;
          dialog: string | undefined;
          jump: string | undefined;
        }>
      | undefined;
    tileTypes: Array<{ name: string; text: string; turn: number | undefined }>;
    itemTypes:
      | Array<{
          name: string;
          tile: string | undefined;
          comestible: boolean | undefined;
          health: number | undefined;
          stamina: number | undefined;
          heat: number | undefined;
          boat: boolean | undefined;
          swimGear: boolean | undefined;
          tip: string | undefined;
          slot: string | undefined;
        }>
      | undefined;
    effectTypes: Array<{ name: string; tile: string | undefined }> | undefined;
  };
  marks: Map<string, number> | undefined;
};

export type WorldColors = {
  base: string;
  lava: string;
  water: string;
  earth: string;
};

export type WorldDescription = {
  player: number | undefined;
  locations: Array<number>;
  types: Array<number>;
  inventories: Map<number, Array<number>> | undefined;
  terrain: Array<number> | undefined;
  healths: Map<number, number> | undefined;
  staminas: Map<number, number> | undefined;
  targetLocations: Map<number, number> | undefined;
  targetEntities: Map<number, number> | undefined;
};

export type WorldMechanicsDescription = {
  agentTypes: Array<{
    name: string;
    tile: string | undefined;
    wanders: string | undefined;
    dialog: Array<string> | undefined;
    health: number | undefined;
    stamina: number | undefined;
    modes:
      | Array<{
          tile: string;
          holds: string | undefined;
          has: string | undefined;
          hot: boolean | undefined;
          cold: boolean | undefined;
          sick: boolean | undefined;
          health: number | undefined;
          stamina: number | undefined;
          immersed: boolean | undefined;
        }>
      | undefined;
    slots:
      | Array<{
          tile: string;
          held: boolean | undefined;
          pack: boolean | undefined;
        }>
      | undefined;
  }>;
  recipes:
    | Array<{
        agent: string;
        reagent: string;
        product: string;
        byproduct: string | undefined;
        price: number | undefined;
        dialog: string | undefined;
      }>
    | undefined;
  actions:
    | Array<{
        agent: string | undefined;
        patient: string;
        left: string | undefined;
        right: string | undefined;
        effect: string | undefined;
        verb: string;
        items: Array<string> | undefined;
        dialog: string | undefined;
        jump: string | undefined;
      }>
    | undefined;
  tileTypes: Array<{ name: string; text: string; turn: number | undefined }>;
  itemTypes:
    | Array<{
        name: string;
        tile: string | undefined;
        comestible: boolean | undefined;
        health: number | undefined;
        stamina: number | undefined;
        heat: number | undefined;
        boat: boolean | undefined;
        swimGear: boolean | undefined;
        tip: string | undefined;
        slot: string | undefined;
      }>
    | undefined;
  effectTypes: Array<{ name: string; tile: string | undefined }> | undefined;
};
